# Generated by Django 3.2 on 2022-03-22 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positions',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
    ]
