# Generated by Django 3.2 on 2022-03-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_app', '0002_alter_positions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='salary_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Информация о выплаченной зарплате'),
        ),
    ]
