# Generated by Django 3.2 on 2022-03-22 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_app', '0003_alter_person_salary_total'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='person',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='Employee_app.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_rating',
            field=models.CharField(choices=[(4, 'base employee'), (3, 'junior manager'), (2, 'middle manager'), (1, 'senior manager'), (0, 'president')], max_length=25, verbose_name='Иерархия'),
        ),
    ]
