# Generated by Django 3.2 on 2022-03-22 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_app', '0004_auto_20220322_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='manager',
            field=models.ForeignKey(default='You boss', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='person', to='Employee_app.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_rating',
            field=models.CharField(choices=[('4', 'base employee'), ('3', 'junior manager'), ('2', 'middle manager'), ('1', 'senior manager'), ('0', 'president')], max_length=25, verbose_name='Иерархия'),
        ),
    ]
