# Generated by Django 3.2 on 2022-03-22 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_app', '0005_auto_20220322_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='manager',
            field=models.ForeignKey(default='You boss', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Employee_app.person'),
        ),
    ]
