# Generated by Django 3.2 on 2022-03-22 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_app', '0006_alter_person_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employee_app.person'),
        ),
    ]
