# Generated by Django 3.2 on 2022-03-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_app', '0008_auto_20220322_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='employment_date',
            field=models.DateField(verbose_name='Дата приема на работу'),
        ),
    ]
