# Generated by Django 3.2 on 2022-03-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_app', '0013_person_salary_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='salary_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='Информация о выплаченной зарплате'),
        ),
    ]
